# =========================
# build stage
# =========================
FROM node:22-alpine AS build

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN apk add --no-cache python3 make g++

RUN npm ci --omit=dev

COPY . .

# =========================
# runtime stage
# =========================
FROM node:22-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache \
    bash \
    ca-certificates \
    curl \
    tzdata \
    ffmpeg

COPY --from=build /usr/src/app /usr/src/app

ENV NODE_ENV=production

EXPOSE 3005
CMD ["bash"]