services:

  nodejs:
    container_name: loc-nodejs
    build:
      context: ./nodejs
      dockerfile: dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./nodejs:/usr/src/app
      - ./tables:/usr/src/tables
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    env_file:
      - .env
    environment:
      MYSQL_PORT: 3306
      MYSQL_HOST: loc-mysql
    depends_on:
      - mysql
    tty: true
    command: npm run dev

  mysql:
    container_name: loc-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./tables/database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:       
  mysql_data: